export  const ADD_INGRDIENT="ADD_INGRDIENT"
export  const REMOVE_INGRDIENT="REMOVE_INGRDIENT"
export const SET_INGRDIENT="SET_INGRDIENT"
export const FETCH_INGRDIENT_FAILD="FETCH_INGRDIENT_FAILD"
export const PURCHTING_ORDER_SUCCESS="PURCHTING_ORDER_SUCCESS"
export const PURCHTING_ORDER_FAILD="PURCHTING_ORDER_FAILD"
export const PURCHTING_ORDER_START="PURCHTING_ORDER_START"

